### ISSUE TITLE
PDF output

### ISSUE THREAD

**Issue by elliottslaughter** [preshing/analyze-spec-benchmarks#2]
I don't know if you care, but I created a branch which has support for PDF output. I didn't actually bother to add any fancy command-line processing so you wouldn't actually want to pull it into the master branch directly though.

https://github.com/elliottslaughter/analyze-spec-benchmarks/commit/df5d96400bf2dbd50fdf16326b3beb2edee6e5ca

**Comment by preshing** [comment]
That's cool. Thank you!
