### ISSUE TITLE
KeyError: 'SPECfp_rate2006'

### ISSUE THREAD

**Issue by mo-ca** [preshing/analyze-spec-benchmarks#4]
Hi,
thanks for the scripts ... I apreciate the work!

Can you please help me out with the following error:

> Analyzing 56100/58082 ...
> Analyzing 56200/58082 ...
> Analyzing 56300/58082 ...
> Traceback (most recent call last):
> 
>   File "<ipython-input-5-3661735af275>", line 1, in <module>
>     runfile('C:/Users/MRMoeR114-admin/Documents/GitHub/analyze-spec-benchmarks/analyze-pages.py', wdir='C:/Users/MRMoeR114-admin/Documents/GitHub/analyze-spec-benchmarks')
> 
>   File "C:\ProgramData\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\ProgramData\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
> 
>   File "C:/Users/MRMoeR114-admin/Documents/GitHub/analyze-spec-benchmarks/analyze-pages.py", line 249, in <module>
>     iterRecords()
> 
>   File "C:/Users/MRMoeR114-admin/Documents/GitHub/analyze-spec-benchmarks/analyze-pages.py", line 231, in iterRecords
>     t, b = func(arg)
> 
>   File "C:/Users/MRMoeR114-admin/Documents/GitHub/analyze-spec-benchmarks/analyze-pages.py", line 186, in parse2006
>     }[benchType]
> 
> KeyError: 'SPECfp_rate2006'
> 
> 

The fetching works perfectly as does the make_graphs.py (tested with the prepared files). 

Thanks in advance

**Comment by preshing** [comment]
Hi mo-ca, if you can get the value of `path` at the time when the exception is raised, it should tell you which file it is failing on. Use a debugger or add some `print` statements.

**Comment by mo-ca** [comment]
Hi preshing,
thanks for your reply. The file raising the error is: 

> \cpu2006\[cpu2006-20170918-49394.txt](https://github.com/preshing/analyze-spec-benchmarks/files/1635292/cpu2006-20170918-49394.txt)

Perhaps they changed the syntax a bit. Can you help with that?

**Comment by preshing** [comment]
Around line 185, try changing:

    benchType = {
        'SPECint_base2000' : 'CINT2000',
        'SPECfp_base2000' : 'CFP2000'
    }[benchType]

to:

    benchType = {
        'SPECint_base2000' : 'CINT2000',
        'SPECfp_base2000' : 'CFP2000',
        'CINT2000' : 'CINT2000',
        'CFP2000' : 'CFP2000'
    }[benchType]

**Comment by preshing** [comment]
The problem is that line 81 of the file you linked doesn't match what `analyze-pages.py` expects. I submitted a possible fix -- it's totally untested, but you can give it a try.

**Comment by mo-ca** [comment]
thanks a lot ... seems to be working
